name: taller_supabase
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # State management
  get: ^4.6.6
  provider: ^6.1.2

  # Date formatting and internationalization
  intl: ^0.20.2

  # Supabase integration
  supabase_flutter: ^2.10.1

  # Environment variables
  flutter_dotenv: ^5.1.0

  # Charts & exports
  fl_chart: ^1.1.1
  path_provider: ^2.1.5
  share_plus: ^12.0.0
  csv: ^6.0.0
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
